### ISSUE TITLE
Cannot retrieve or connect to BLEGeneralIO created as tutorial

### ISSUE THREAD

**Issue by majik00027** [SAndroidEOfficial/framework#45]
Tutorial [link](https://github.com/SAndroidEOfficial/framework/wiki/01-Getting-Started
).

We are sure about the arduino flashing and project creating processes;

Working on v0.6 and trying to access setDigitalValue() on previously created  global BLEGeneralIO objects(Attempting to switch leds on a breadboard).

Link to my code: [github Link](https://github.com/majik00027/SandrAppKeys)

Error report:
`05-12 17:16:47.136 24965-24965/sandroide.sadre E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: sandroide.sadre, PID: 24965
                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/altbeacon/beacon/BeaconManager;
                                                                     at it.unibs.sandroide.lib.activities.SandroideApplication.onCreate(SandroideApplication.java:58)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4561)
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.altbeacon.beacon.BeaconManager" on path: DexPathList[[zip file "/data/app/sandroide.sadre-2/base.apk", zip file "/data/app/sandroide.sadre-2/split_lib_dependencies_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_0_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_1_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_2_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_3_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_4_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_5_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_6_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_7_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_8_apk.apk", zip file "/data/app/sandroide.sadre-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                     at it.unibs.sandroide.lib.activities.SandroideApplication.onCreate(SandroideApplication.java:58) 
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4561) 
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:147) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
                                                                 	Suppressed: java.lang.ClassNotFoundException: org.altbeacon.beacon.BeaconManager
                                                                     at java.lang.Class.classForName(Native Method)
                                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                     		... 13 more
                                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by bgkerion** [comment]
Hi, thank you for your question. In version 6.0 it is mandatory to enable supports for beacons in the gradle file but it wasn't specified into the base tutorial. I've already fixed the tutorial, you have to add this code to your grade file and everything should be fixed:
Now, add the additional Altbeacon library to the dependencies in our [build.gradle](https://github.com/SAndroidEOfficial/sandroide-beacons/blob/master/example-app/app/build.gradle) file.

```
     ...
     dependencies {
          ...
          compile 'org.altbeacon:android-beacon-library:2.9.2'
          ...
     }
     ...
```
Let us know if it is enough...

**Comment by giowild** [comment]
Please open this again if the issue is still not solved.
